---
title: "CO2ProdScript"
author: "Rose Abramoff"
date: "8/6/2018"
output: html_document
---
```
This script calculates CO2 production from CO2 concentration outputted by the model, intended to test inversion methods used by empirical scientists. The model calculates heterotrophic respiration directly, allowing for comparisons CO2 production calculated by inveresion and CO2 production by microbes, and their temperature sensitivity. 
This scripts uses the inversion method of Hicks Pries et al. 2017 Science, and is also heavily based on their original R script for calculating production fluxes from gas well measurements at Blodgett Experimental Forest.
```
#Libraries
```{r}
library(plyr)
library(MASS)
library(reshape2)
library(car)
library(ggplot2)
library(nlme)
library(bbmle)
library(doBy)
library(rootSolve)
library(splines)
library(ncdf4)

sterr = function(x) sqrt(var(x,na.rm=TRUE)/length(na.omit(x)))
```

##Load seasonal daily model output
```{r}
rundir = "/Users/rzabramoff/Documents/BigModels/runs_from_edison/" #model output directory
dayfolder = c("NSCEAH","NSCEWH") #name of folder
nyear = c(1, 1) #number of years of model run
nskip = c(1, 1) #number of years skipped between output files

deepmat.1d=deepmat.2d.15=deepmat.2d.10=NULL
out.string.1d <- c("TOTSOMC","TOTSOMC_1m","HR","CO2x_FLX_SURFEMI","TSOI_10CM")
out.string.2d.15 <- c("SOILPSI", "HR_vr")
out.string.2d.10 <- c("CO2x_TRACER_CONC_BULK")   
in.soil.1d=in.soil.2d.15=in.soil.2d.10=NULL

#The output size for this experiment is hardcoded below (729 days) - may need to modify
for (j in 1:length(dayfolder)) {
  for(i in 1:length(out.string.1d)){
  in.soil.1d[[i]] <- vector(length = 729)
  }
  for(i in 1:length(out.string.2d.15)){
  in.soil.2d.15[[i]] <- matrix(nrow=729, ncol=15)
  }
  for(i in 1:length(out.string.2d.10)){
  in.soil.2d.10[[i]] <- matrix(nrow=729, ncol=10)
  }

        filename <- paste(rundir,dayfolder[j],"/",dayfolder[j],".clm2.h0.2013-10-24-00000.nc", sep = "")

        in.file <- nc_open(filename)
        
        for(k in 1:length(out.string.1d)){
        in.soil.1d[[k]] <- ncvar_get(in.file, out.string.1d[k])
        }
        for(k in 1:length(out.string.2d.15)){
        in.soil.2d.15[[k]] <- ncvar_get(in.file, out.string.2d.15[k])
        }
        for(k in 1:length(out.string.2d.10)){
        in.soil.2d.10[[k]] <- ncvar_get(in.file, out.string.2d.10[k])
        }

        rm(in.file)

deepmat.1d[[j]] = in.soil.1d
deepmat.2d.15[[j]] = in.soil.2d.15
deepmat.2d.10[[j]] = in.soil.2d.10
names(deepmat.1d[[j]]) <- out.string.1d
names(deepmat.2d.15[[j]]) <- out.string.2d.15
names(deepmat.2d.10[[j]]) <- out.string.2d.10
}
names(deepmat.1d) <- dayfolder
names(deepmat.2d.15) <- dayfolder
names(deepmat.2d.10) <- dayfolder

rm(in.soil.1d, in.soil.2d.10, in.soil.2d.15)
```

##Organize data frame
```{r}
depth.m = c(0.00710, 0.0279, 0.0623, 0.119, 0.212, 0.366, 0.620, 1.038, 1.728, 2.865, 4.739, 7.830, 12.925, 21.326, 35.178)
depm <- depth.m[1:8]*100

co2.ambient <- deepmat.2d.10[["NSCEAH"]]$CO2x_TRACER_CONC_BULK[1:8,]*44*1000*0.516 #quick conv from mol CO2/m3 to ppm
co2.heated <- deepmat.2d.10[["NSCEWH"]]$CO2x_TRACER_CONC_BULK[1:8,]*44*1000*0.516
rownames(co2.ambient) <- depm  
colnames(co2.ambient) <- 1:729
rownames(co2.heated) <- depm  
colnames(co2.heated) <- 1:729

mod <- rbind(melt(co2.ambient),melt(co2.heated))
names(mod) <- c("Depth","Day","CO2")
mod$Treatment <- c(rep("Control",dim(melt(co2.ambient))[1]),rep("Heated",dim(melt(co2.heated))[1]))
        
##Use depth (cm) to calculate Bulk Density and porosity
mod$BD=-0.0001291*mod$Depth^2+0.0217277*mod$Depth+0.6326013
#assume particle density is 2.65 g/cm3 (if pure sand is 2.65)
mod$por=(1-(mod$BD/2.65))

plot(BD~Depth, mod)
plot(por~Depth, mod)

mod$Depth.m=mod$Depth/100

ggplot(mod) +
  geom_point(aes(x=CO2, y=Depth.m, colour=Treatment))+
  theme_bw() +      
  xlab("CO2") +
  ylab("Depth") +
  theme(axis.text.x=element_text(size=14, colour="black"),
        axis.text.y=element_text(size=14, colour="black"),
        axis.title.y=element_text(size=16, colour="black"),
        axis.title.x=element_blank(),
        panel.border=element_blank(), 
        axis.line=element_line(colour="black"))+
  scale_y_reverse(breaks=seq(0, .90, .10))

mod$ID <- paste(mod$Day,mod$Treatment)

#Package data as monthly so don't overload memory
mod$Time = seq(as.POSIXlt("2013-10-24 20:22:00 GMT"),as.POSIXlt("2015-12-24 20:22:00 GMT"),length=729)
mod$Month = format(mod$Time, format="%m")
mod <- ddply(mod, .(Month,Depth,Treatment), summarise, CO2=mean(CO2), BD=mean(BD), por=mean(por), Depth.m=mean(Depth.m))
mod$ID <- paste(mod$Month,mod$Treatment)
```

##Predict CO2 concentration
```{r}
#second order polynomial by treatment and time
C_values=lmList(CO2~poly(Depth.m, 2, raw=TRUE)|ID, data=mod,na.action=na.omit)  
C_values3=lmList(CO2~poly(Depth.m, 3, raw=TRUE)|ID, data=mod,na.action=na.omit)  
C_values4=lmList(CO2~poly(Depth.m, 4, raw=TRUE)|ID, data=mod,na.action=na.omit)

AIC(C_values, C_values3, C_values4)

#check model fit
ID=rep(levels(as.factor(mod$ID)), each=1000)
Depth.m=rep(seq(0, 0.9,length.out=1000),length(levels(as.factor(mod$ID))))
pred.frame=data.frame(cbind(ID, Depth.m))
pred.frame$Depth.m=as.numeric(as.character(pred.frame$Depth.m))
pred.frame$CO2=predict(C_values4, pred.frame)

ggplot(mod) +
  geom_point(aes(x=CO2, y=Depth.m, colour=ID, shape=Treatment))+
  theme_bw() +      #makes bg white
  xlab("CO2") +
  ylab("Depth") +
  theme(axis.text.x=element_text(size=14, colour="black"),
        axis.text.y=element_text(size=14, colour="black"),
        axis.title.y=element_text(size=16, colour="black"),
        axis.title.x=element_blank(),
        panel.border=element_blank(), 
        axis.line=element_line(colour="black"))+
  geom_point(data=pred.frame, aes(x=CO2, y=Depth.m, colour=ID), size=.5)+
  scale_y_reverse(breaks=seq(0, .90, .10))
```

##Calculate CO2 for discrete depth intervals
```{r}
#For second order polynomial
C_coef=nlme:::coef.lmList(C_values4)
C_coef<-data.frame(as.character(rownames(C_coef)),C_coef)

names(C_coef)=c("ID","intercept", "p1", "p2", "p3", "p4")

C_coeff_depths <- c(0.0071, 0.0279, 0.0623, 0.1190, 0.2120, 0.3660, 0.6200, 1.0380)

pred.from.coefs <- function(x){
  C_coef$p4*4*x + C_coef$p3*3*x + C_coef$p2*2*x + C_coef$p1
}

C_coef$C_007=pred.from.coefs(C_coeff_depths[1])
C_coef$C_03=pred.from.coefs(C_coeff_depths[2])
C_coef$C_06=pred.from.coefs(C_coeff_depths[3])
C_coef$C_12=pred.from.coefs(C_coeff_depths[4])
C_coef$C_21=pred.from.coefs(C_coeff_depths[5])
C_coef$C_37=pred.from.coefs(C_coeff_depths[6])
C_coef$C_62=pred.from.coefs(C_coeff_depths[7])
C_coef$C_104=pred.from.coefs(C_coeff_depths[8])

#melt so one line per depth
drops <- c("intercept","p1","p2","p3","p4")
dataC_final=C_coef[ , !(names(C_coef) %in% drops)]
dataC_final=melt(dataC_final[,c(1:9)], id="ID")
dataC_final$ID=as.character(dataC_final$ID)
names(dataC_final)=c("ID", "variable", "CO2_ppm.per.m.poly")

#####Calculate CO2 ppm per m discretely####
names(mod)
data_f=reshape(mod, idvar=c("ID", "Treatment", "Month"), timevar="Depth.m", direction="wide")
names(data_f)

data_f$C_007=(data_f$CO2.0.0279-data_f$CO2.0.0071)/(.0279-.0071)
data_f$C_03=(data_f$CO2.0.0623-data_f$CO2.0.0279)/(.0623-.0279)
data_f$C_06=(data_f$CO2.0.119-data_f$CO2.0.0623)/(.119-.0623)
data_f$C_12=(data_f$CO2.0.212-data_f$CO2.0.119)/(.212-.119)
data_f$C_21=(data_f$CO2.0.366-data_f$CO2.0.212)/(.366-.212)
data_f$C_37=(data_f$CO2.0.62-data_f$CO2.0.366)/(.62-.366)
data_f$C_62=(data_f$CO2.0.62-data_f$CO2.0.366)/(1.038-.62)
data_f$C_104=0

#melt so one line per depth
dataC_final3=data_f[,c("ID","C_007","C_03","C_06","C_12","C_21","C_37","C_62","C_104")]
dataC_final3=melt(dataC_final3[,c(1:9)], id="ID")
dataC_final3$ID=as.character(dataC_final3$ID)
names(dataC_final3)=c("ID", "variable", "CO2_ppm.per.m.dis")

dataC_final=merge(dataC_final, dataC_final3, by=c("ID", "variable"))

dataC_final$variable=revalue(dataC_final$variable, c("C_007"=.0071, "C_03"=.0279, "C_06"=.0623, "C_12"=.119, "C_21"=.212, "C_37"=.366, "C_62"=.62, "C_104"=1.038))

dataC_final$Depth=as.numeric(levels(dataC_final$variable))[dataC_final$variable]
```

##Modeled soil temperature
```{r}
temp.ambient <- deepmat.1d[["NSCEAH"]]$TSOI_10CM
temp.heated <- deepmat.1d[["NSCEWH"]]$TSOI_10CM
rownames(temp.ambient) <- 1:729
rownames(temp.heated) <- 1:729

temp.df <- rbind(melt(temp.ambient),melt(temp.heated))
names(temp.df) <- c("Day","Temp")
temp.df$Treatment <- c(rep("Control",dim(melt(temp.ambient))[1]),rep("Heated",dim(melt(temp.heated))[1]))

#average by month
temp.df$Time = seq(as.POSIXlt("2013-10-24 20:22:00 GMT"),as.POSIXlt("2015-12-24 20:22:00 GMT"),length=729)
temp.df$Month = format(temp.df$Time, format="%m")
temp.df <- ddply(temp.df, .(Month,Treatment), summarise, Temp=mean(Temp))
temp.df$ID <- paste(temp.df$Month,temp.df$Treatment)
```

##Modeled soil moisture
```{r}
psi.ambient <- deepmat.2d.15[["NSCEAH"]]$SOILPSI[1:8,]
psi.heated <- deepmat.2d.15[["NSCEWH"]]$SOILPSI[1:8,]
rownames(psi.ambient) <- depm  
colnames(psi.ambient) <- 1:729
rownames(psi.heated) <- depm  
colnames(psi.heated) <- 1:729

psi.df <- rbind(melt(psi.ambient),melt(psi.heated))
names(psi.df) <- c("Depth","Day","psi")
psi.df$Treatment <- c(rep("Control",dim(melt(psi.ambient))[1]),rep("Heated",dim(melt(psi.heated))[1]))

#average by month
psi.df$Time = seq(as.POSIXlt("2013-10-24 20:22:00 GMT"),as.POSIXlt("2015-12-24 20:22:00 GMT"),length=729)
psi.df$Month = format(psi.df$Time, format="%m")
psi.df <- ddply(psi.df, .(Month,Depth,Treatment), summarise, psi=mean(psi), 
             Depth=mean(Depth)/100)
psi.df$ID <- paste(psi.df$Month,psi.df$Treatment)

psi.df$BD=-0.0001291*(psi.df$Depth*100)^2+0.0217277*(psi.df$Depth*100)+0.6326013
psi.df$por=(1-(psi.df$BD/2.65))
```

##CO2 flux density
```{r}
#merge temp and soil psi
data_final=merge(temp.df, dataC_final, by=c("ID"))

data_final=merge(psi.df, data_final, by=c("ID", "Depth"))
data_final$VWC = -data_final$psi*0.05 #Important Note! This is not a real conversion - I just imposed the following relationship so that I could generate example plots. In the future, we will need to generate VWC as a model output.

###calculate molar density in umol m-3 air
data_final$md.air=(868/1000)/((8.3144621*10^-5)*(data_final$Temp+273))

###calculate Diffusion
#calculate tortuosity(using equation based on diffusion experiment)
data_final$af.por=(data_final$por-data_final$VWC) #proportion of air-filled pores
plot(af.por~Depth, data_final)

data_final$af.por=ifelse(data_final$af.por>0, data_final$af.por, 0.001)

data_final$tor=0.95*data_final$af.por^1.93 #Moyes equation

##graph tortuosity calculations
por=seq(0.41, 0.8, by=0.01)
VWC=rep(seq(0, 0.4, by=0.1), 8)
af.por=por-VWC

tor_AM=0.95*af.por^1.93
tor_Mill=af.por^(4/3)*(af.por/por)^2

tor_data=cbind(por,VWC, af.por, tor_AM, tor_Mill)
plot(tor_AM~af.por, tor_data) #check data
points(tor_Mill~af.por, tor_data, col="blue")

plot(af.por~Depth, data_final) #check data
plot(tor~Depth, data_final) #check data

data_final$D.o=14.7*((data_final$Temp+273)/293.15)^1.75*(101.3/(868/10))  #14.7 mm2 s-1 is the diffusion of CO2 in air at 293.15K and 101.3 kPa, from Vargas et al. 2010

data_final$D=data_final$tor*data_final$D.o

#Calculate flux density across a horizontal plane
data_final$CO2_md.per.m.poly=data_final$md.air*data_final$CO2_ppm.per.m.poly
data_final$CO2_md.per.m.dis=data_final$md.air*data_final$CO2_ppm.per.m.dis

data_final$Flux.d.poly=-1*data_final$D*data_final$CO2_md.per.m.poly/(1000^2) #divide by 1000^2 b/c D was in mm^2/s
data_final$Flux.d.dis=-1*data_final$D*data_final$CO2_md.per.m.dis/(1000^2) 

#summarize F
data_avg=summaryBy(Flux.d.dis~c(Depth, yrmo, Treatment), data=data_final, FUN=function(x) c(m=mean(x,na.rm=T), se=sterr(x)))

fluxpalette=c("blue", "red")

ggplot(data_final, aes(y=Depth, x=Flux.d.poly, group=Month.x, col=Treatment.x)) + 
  geom_point() +
  theme_bw() +    
  xlab("CO2 Flux Density") +
  ylab("Depth") +
  scale_colour_manual(values=fluxpalette)+
  theme_bw()+
  theme(axis.text.x=element_text(size=16, colour="black"),
        axis.text.y=element_text(size=16, colour="black"),
        axis.title.x=element_text(size=18, colour="black"),
        axis.title.y=element_text(size=18, colour="black"),
        legend.title=element_text(size=16),
        legend.text=element_text(size=16),
        panel.grid=element_blank(),
        panel.border=element_blank(), 
        legend.position="none",
        axis.line=element_line(colour="black"))+
  scale_y_reverse(breaks=seq(0, 100, 10))

####take difference between layers to get CO2 production divided by depth in meters (so umol m-3 s-1)####
data_f2=reshape(data_final, idvar=c("ID", "Treatment.x", "Month.x"), timevar="Depth", direction="wide")
names(data_f2)

data_f2$CO2_prod.poly_0.0071=(data_f2$Flux.d.poly.0.0071-data_f2$Flux.d.poly.0.0279)/(.0071-.0279)
data_f2$CO2_prod.poly_0.0279=(data_f2$Flux.d.poly.0.0279-data_f2$Flux.d.poly.0.0623)/(.0279-.0623)
data_f2$CO2_prod.poly_0.0623=(data_f2$Flux.d.poly.0.0623-data_f2$Flux.d.poly.0.119)/(.0623-.119)
data_f2$CO2_prod.poly_0.119=(data_f2$Flux.d.poly.0.119-data_f2$Flux.d.poly.0.212)/(.119-.212)
data_f2$CO2_prod.poly_0.212=(data_f2$Flux.d.poly.0.212-data_f2$Flux.d.poly.0.366)/(.212-.366)
data_f2$CO2_prod.poly_0.366=(data_f2$Flux.d.poly.0.366-data_f2$Flux.d.poly.0.62)/(.366-.62)
data_f2$CO2_prod.poly_0.62=(data_f2$Flux.d.poly.0.62-data_f2$Flux.d.poly.1.038)/(.62-1.038)

data_f2$CO2_prod.dis_0.0071=(data_f2$Flux.d.dis.0.0071-data_f2$Flux.d.dis.0.0279)/(.0071-.0279)
data_f2$CO2_prod.dis_0.0279=(data_f2$Flux.d.dis.0.0279-data_f2$Flux.d.dis.0.0623)/(.0279-.0623)
data_f2$CO2_prod.dis_0.0623=(data_f2$Flux.d.dis.0.0623-data_f2$Flux.d.dis.0.119)/(.0623-.119)
data_f2$CO2_prod.dis_0.119=(data_f2$Flux.d.dis.0.119-data_f2$Flux.d.dis.0.212)/(.119-.212)
data_f2$CO2_prod.dis_0.212=(data_f2$Flux.d.dis.0.212-data_f2$Flux.d.dis.0.366)/(.212-.366)
data_f2$CO2_prod.dis_0.366=(data_f2$Flux.d.dis.0.366-data_f2$Flux.d.dis.0.62)/(.366-.62)
data_f2$CO2_prod.dis_0.62=(data_f2$Flux.d.dis.0.62-data_f2$Flux.d.dis.1.038)/(.62-1.038)

data_f2$T_0.0071=(data_f2$Temp.0.0071+data_f2$Temp.0.0279)/(2)
data_f2$T_0.0279=(data_f2$Temp.0.0279+data_f2$Temp.0.0623)/(2)
data_f2$T_0.0623=(data_f2$Temp.0.0623+data_f2$Temp.0.119)/(2)
data_f2$T_0.119=(data_f2$Temp.0.119+data_f2$Temp.0.212)/(2)
data_f2$T_0.212=(data_f2$Temp.0.212+data_f2$Temp.0.366)/(2)
data_f2$T_0.366=(data_f2$Temp.0.366+data_f2$Temp.0.62)/(2)
data_f2$T_0.62=(data_f2$Temp.0.62+data_f2$Temp.1.038)/(2)

data_f2$VWC_0.0071=(data_f2$VWC.0.0071+data_f2$VWC.0.0279)/(2)
data_f2$VWC_0.0279=(data_f2$VWC.0.0279+data_f2$VWC.0.0623)/(2)
data_f2$VWC_0.0623=(data_f2$VWC.0.0623+data_f2$VWC.0.119)/(2)
data_f2$VWC_0.119=(data_f2$VWC.0.119+data_f2$VWC.0.212)/(2)
data_f2$VWC_0.212=(data_f2$VWC.0.212+data_f2$VWC.0.366)/(2)
data_f2$VWC_0.366=(data_f2$VWC.0.366+data_f2$VWC.0.62)/(2)
data_f2$VWC_0.62=(data_f2$VWC.0.62+data_f2$VWC.1.038)/(2)
```

##CO2 Production
```{r}
#melt variables individually so prod, Temp, and VWC in wide format
data_f3=data_f2[,c(1:3,156:162)]
data_f3=melt(data_f3[,c(1:10)], id=c("ID", "Treatment.x", "Month.x"))
names(data_f3)=c("ID", "Treatment.x", "Month.x", "variable", "CO2_prod.poly")

data_f3c=data_f2[,c(1:3,163:169)]
data_f3c=melt(data_f3c[,c(1:10)], id=c("ID", "Treatment.x", "Month.x"))
names(data_f3c)=c("ID", "Treatment.x", "Month.x", "variable", "CO2_prod.dis")

data_f3T= data_f2[,c(1:3,170:176)]
data_f3T=melt(data_f3T[,c(1:10)], id=c("ID", "Treatment.x", "Month.x"))
names(data_f3T)=c("ID", "Treatment.x", "Month.x", "variable", "Temp")

data_f3V=data_f2[,c(1:3,177:183)]
data_f3V=melt(data_f3V[,c(1:10)], id=c("ID", "Treatment.x", "Month.x"))
names(data_f3V)=c("ID", "Treatment.x", "Month.x", "variable", "VWC")

data_f3=cbind(data_f3[,c(1:5)], data_f3c[,c(5)], data_f3T[,c(5)], data_f3V[,c(5)])
names(data_f3)=c("ID", "Treatment.x", "Month.x", "variable", "CO2_prod.poly", "CO2_prod.dis", "Temp", "VWC")

data_f3$variable=revalue(data_f3$variable, c("CO2_prod.poly_0.0071"=0.0071, "CO2_prod.poly_0.0279"=0.0279, "CO2_prod.poly_0.0623"=0.0623, "CO2_prod.poly_0.119"=0.119, "CO2_prod.poly_0.212"=0.212, "CO2_prod.poly_0.366"=0.366, "CO2_prod.poly_0.62"=0.62))
names(data_f3)
data_f3$Depth=as.numeric(levels(data_f3$variable))[data_f3$variable]

#remove negative production values
data_f3$CO2_prod.poly=ifelse(data_f3$CO2_prod.poly>0, data_f3$CO2_prod.poly, 0)
data_f3$CO2_prod.dis=ifelse(data_f3$CO2_prod.dis>0, data_f3$CO2_prod.dis, 0)

##Summarize and graph, all points
fluxpalette=c("dodgerblue", "firebrick")

ggplot(data_f3, aes(y=Depth, x=CO2_prod.poly, col=Treatment.x)) + 
  geom_point() +
  theme_bw() +      #makes bg white
  xlab("CO2 Production(umol C m-2 s-1)") +
  ylab("Depth") +
  scale_colour_manual(values=fluxpalette)+
  theme_bw()+
  theme(axis.text.x=element_text(size=16, colour="black"),
        axis.text.y=element_text(size=16, colour="black"),
        axis.title.x=element_text(size=18, colour="black"),
        axis.title.y=element_text(size=18, colour="black"),
        legend.title=element_text(size=16),
        legend.text=element_text(size=16),
        panel.grid=element_blank(),
        panel.border=element_blank(), 
        legend.position="none",
        axis.line=element_line(colour="black"))+
  scale_y_reverse(breaks=seq(0, 100, 10))

##Summarize and graph, by treatment
data_avg.poly=summaryBy(CO2_prod.poly ~c(Depth, Treatment.x), data=data_f3, FUN=function(x) c(m=mean(x,na.rm=T), se=sterr(x)))
data_avg.dis=summaryBy(CO2_prod.dis ~c(Depth, Treatment.x), data=data_f3, FUN=function(x) c(m=mean(x,na.rm=T), se=sterr(x)))

data_avg=cbind(data_avg.poly, data_avg.dis[,3:4])

fluxpalette=c("dodgerblue", "firebrick")

ggplot(data_avg) + 
  geom_point(aes(y=Depth, x=CO2_prod.poly.m, shape=Treatment.x), size=6, col="red") +
  geom_point(aes(y=Depth, x=CO2_prod.dis.m, shape=Treatment.x), size=6, col="green") +
  theme_bw() +      #makes bg white
  xlab(expression(paste("CO2 Production"~"(umol C ",m^{-2},s^{-1},")")))+
  ylab("Depth (cm)") +
  scale_colour_manual(values=fluxpalette)+
  theme_bw()+
  theme(axis.text.x=element_text(size=16, colour="black"),
        axis.text.y=element_text(size=16, colour="black"),
        axis.title.x=element_text(size=18, colour="black"),
        axis.title.y=element_text(size=18, colour="black"),
        legend.title=element_text(size=16),
        legend.text=element_text(size=16),
        panel.grid=element_blank(),
        panel.border=element_blank(), 
        legend.position="none",
        axis.line=element_line(colour="black"))+
  scale_y_reverse(breaks=seq(0, 100, 20))
```





